# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-26 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_auto_20180926_1217'),
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='room_n',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='room.Room'),
        ),
    ]
