# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-26 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_userinfo_room_n'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='ucoin',
            field=models.IntegerField(verbose_name='金币'),
        ),
    ]
