# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-03 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20180926_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='ucoin',
            field=models.IntegerField(default=5000, null=True, verbose_name='金币'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='uimg',
            field=models.ImageField(null=True, upload_to='touxiang', verbose_name='头像'),
        ),
    ]
