# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-04 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20181003_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='addr',
            field=models.CharField(default='127.0.0.1:8000', max_length=20, verbose_name='ip地址'),
        ),
    ]
