# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-09 08:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_userinfo_addr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='addr',
        ),
    ]
