# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-26 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('room', '0001_initial'),
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, null=True, verbose_name='牌')),
                ('room_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='room.Room')),
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='index.UserInfo')),
            ],
        ),
    ]
