# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-09 08:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_remove_userinfo_addr'),
        ('room', '0003_room_number'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='room_name',
        ),
        migrations.RemoveField(
            model_name='game',
            name='user_name',
        ),
        migrations.AddField(
            model_name='game',
            name='room_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='room.Room'),
        ),
        migrations.AddField(
            model_name='game',
            name='serial_number',
            field=models.IntegerField(default=0, verbose_name='序号'),
        ),
        migrations.AddField(
            model_name='game',
            name='user_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.UserInfo'),
        ),
    ]
