# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-09 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20181009_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='brand',
            field=models.CharField(max_length=500, null=True, verbose_name='牌'),
        ),
    ]
