# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-26 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=10, verbose_name='房间名')),
                ('state', models.BooleanField(default=True, verbose_name='状态')),
                ('room_root', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='index.UserInfo')),
            ],
        ),
    ]
