# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-26 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_root',
            field=models.CharField(max_length=10, verbose_name='房主'),
        ),
    ]
